### ISSUE TITLE
certbot-dns-dynu broken with certbot 2.0.0

### ISSUE THREAD

**Issue by lprimak** [bikram990/certbot-dns-dynu#4]
Hi, the plugin has been working great, but broke on certbot 2.0
Thank you!

```
admin@nova ~ % certbot --version
An unexpected error occurred:
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
```

**Comment by avivgr** [comment]
Happened here as well

```
...
an unexpected error occurred:
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-qz7ll5g8/log or re-run Certbot with -v for more details.
[root@docker-cd9cae702edc:/app]# cat /tmp/certbot-log-qz7ll5g8/log
2022-11-23 07:48:50,845:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1707, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/plugins/disco.py", line 208, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/plugins/disco.py", line 215, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/plugins/disco.py", line 56, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/certbot_dns_dynu/dns_dynu.py", line 17, in <module>
    @zope.interface.implementer(interfaces.IAuthenticator)
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
2022-11-23 07:48:50,845:ERROR:certbot._internal.log:An unexpected error occurred:
2022-11-23 07:48:50,845:ERROR:certbot._internal.log:AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
```

**Comment by lprimak** [comment]
FYI I tried both Python 3.10 and 3.11 and have the same issue.
